### ISSUE TITLE
Touchbar causes stacktrace on resume in debugger

### ISSUE THREAD

**Issue by bertramn** [olivernybroe/intellij-touch#18]
Hey, I setup a very simple touch bar context to resume debug but when I am trying to use this, I am greeted by below stack trace.

## Expected Behavior

Debug resume continues

## Actual Behavior

```
null
java.lang.NullPointerException
	at com.intellij.debugger.actions.ResumeThreadAction.actionPerformed(ResumeThreadAction.java:40)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at dk.lost_world.intellij_touch.Components.ComponentBuilder.runAction(ComponentBuilder.java:63)
	at dk.lost_world.intellij_touch.Components.ButtonBuilder.lambda$null$0(ButtonBuilder.java:97)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

## Steps to Reproduce the Problem

  1. install plugin and restart
  1. configure debug action resume in appearance panel
  1. run a plain java debug with break point and press resume on touch bar

## Specifications

  - Plugin Version: v0.5.2
  - Platform: MacOS 10.13.4
  - Platform Version: Idea 2018.4 (latest release)

**Comment by olivernybroe** [comment]
@bertramn Thanks for reporting. However I am not maintaining this anymore as IntelliJ has added support for the Touch bar with customization like ours.
